### ISSUE TITLE
depth to normal

### ISSUE THREAD

**Issue by mtzhang1999** [danielgordon10/dg_util#8]
Hi! Thanks for your contributions!
I am trying to get some surface normal map from depth data. I found this https://github.com/danielgordon10/dg_util/blob/master/dg_util/python_utils/pytorch_util.py#L872 may help but I do not know how to get the normal map through this code. Would you please tell me in detail?

Thanks in advance!

**Comment by danielgordon10** [comment]
Depth should be a 2D torch tensor depth image.
